### ISSUE TITLE
Editor Vulnerability

### ISSUE THREAD

**Issue by ColinTimBarndt** [sandstone-mc/sandstone-documentation#6]
It is possible to execute any code from the interactive snippets in the website's context because the compiler function `compileDataPack` only calls `eval()` on the transpiled code. This is very unsafe and something I would classify as vulnerable. Just paste this into a snippet: `alert(location.origin)`. It would be more secure to execute the code in a sandbox, there are libraries for that.

But I don't think that this vulnerability has much impact because the docs site has no login/credentials or anything similar.

**Comment by ColinTimBarndt** [comment]
And I just found out that the scope of the code of course includes the scope of the compiler function, so it's for example possible to get variables from that scope:

`alert(eval("imports"))`

And the locked import statement at the top can be extended by the full functionality of sandstone:

```ts
const {tellraw, Selector} = eval("sandstone");
MCFunction("test", () => {
  tellraw(Selector("@a"), "I am free!")
});
```

**Comment by MulverineX** [comment]
Before #9 this would've probably been closed as not planned because its client-side javascript, if the user can do funny stuff with it that doesn't really matter. But, since #9 introduced a worker thread for the interactive snippets, this should no longer be a problem at all.
